version: "3.9"
services:
  python:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    # command: python3 main.py
    command: whisper --help | findstr -i pytorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              count: 1
              capabilities: [gpu]