version: "3.9"
services:
  my-whisper:
    build: .
    image: my-whisper:0.1
    volumes:
      - ./app:/app
    working_dir: /app
    command: python3 main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              capabilities: [gpu]
              # count: 1