version: "3.9"
services:
  whisper:
    build: .
    volumes:
      - ./cache:/root/.cache/whisper:rw
      - ./app:/code/app
    ports:
      - "80:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              capabilities: [gpu]
              count: 1