version: "3.9"
services:
  my-whisper:
    # build: .
    image: test
    volumes:
      - ./app:/app
    working_dir: /app
    command: python3 main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              capabilities: [gpu]
              count: 1