version: "3.9"
services:
  whisper:
    build: .
    # image: whisper:0.1
    command: python3 main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              capabilities: [gpu]
              count: 1