name: staging
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Gitlab
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: backend staging build, tag, and push image to gitlab ECR
        env:
          ECR_REGISTRY: gitlab.xgridcolo.com:5050/ecr
          ECR_REPOSITORY: whisper-backend-staging
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: backend Checkout argocd
        uses: actions/checkout@v2
        with:
          repository: teamsmiley/argocd-c3
          token: ${{ secrets.PAT }}

      - name: backend replace staging image version number to sha
        run: |
          cd apps/whisper-staging
          sed "s/:latest/:${{ github.sha }}/g" 31.api.origin > 31.api.yml

      - name: backend Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "push new tag"
          git push
