name: production
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: backend Checkout
        uses: actions/checkout@v2

      - name: backend prod build, tag, and push image to gitlab ECR
        env:
          ECR_REGISTRY: ${{secrets.registry}}/ecr
          ECR_REPOSITORY: whisper-backend-prod
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: backend Checkout argocd
        uses: actions/checkout@v2
        with:
          repository: teamsmiley/argocd-c3
          token: ${{ secrets.PAT }}

      - name: backend replace prod image version number to sha
        run: |
          cd apps/whisper-prod
          sed "s/:latest/:${{ github.sha }}/g" 31.api.origin > 31.api.yml

      - name: backend Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "push new tag"
          git push
